CUDA_VISIBLE_DEVICES=7 python test.py \
  --gpu_ids 0 \
  --batchSize 1 \
  --static \
  --name kitti_test \
  --dataset 'kitti' \
  --ngf 64 \
  --loadSize 256 \
  --tOut 3 \
  --ImagesRoot "./data/kitti/raw_data_256p/" \
  --SemanticRoot "./data/kitti/semantic/" \
  --StaticMapDir "./data/kitti/dynamic/" \
  --InstanceRoot "/disk1/yue/kitti/instance_upsnet/" \
  --non_rigid_dir "/disk1/yue/kitti/non_rigid_mask/val/" \
  --small_object_mask_dir "/disk1/yue/kitti/small_object_mask/val/" \
  --load_pretrain "./checkpoints/kitti/" \
  --how_many 2000
