CUDA_VISIBLE_DEVICES=5,6 python train_city.py \
  --gpu_ids 0,1 \
  --batchSize 4 \
  --name city \
  --n_scales_temporal 1 \
  --ngf 32 \
  --lr 1e-4 \
  --loadSize 1024 \
  --lambda_D 4.0 \
  --lambda_D_T 4.0 \
  --lambda_scale 1.0 \
  --lambda_shear 1.0 \
  --lambda_rotation 1.0 \
  --lambda_translationx 0.1 \
  --lambda_translationy 0.8 \
  --lambda_image 1.0 \
  --ImagesRoot "./data/cityscapes/leftImg8bit_sequence_512p/" \
  --SemanticRoot "./data/cityscapes/semantic/"
