CUDA_VISIBLE_DEVICES=6 python train.py \
  --gpu_ids 0 \
  --batchSize 1 \
  --name city \
  --ngf 64 \
  --static \
  --lr 2e-4 \
  --loadSize 512 \
  --niter 60 \
  --lambda_D 1.0 \
  --lambda_D_T 1.0 \
  --lambda_F 1.0 \
  --lambda_VGG 15.0 \
  --lambda_smooth 1.0 \
  --lambda_feat 15.0 \
  --niter_decay 20 \
  --ImagesRoot "./data/cityscapes/leftImg8bit_sequence_512p/" \
  --SemanticRoot "./data/cityscapes/semantic/" \
  --StaticMapDir "./data/cityscapes/dynamic_tracking_mask/" \
  --InstanceRoot "./data/cityscapes/instance_upsnet/" \
  --load_pretrain "./checkpoints/cityscapes/"
